openapi: 3.0.0
info:
  title: nextjs-startup-kit API
  description: nextjs-startup-kit API
  version: 0.1.0
servers:
  - url: http://api.nextjs-startup-kit.com/v1
    description: api server
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
